server:
  servlet:
    session:
      tracking-modes: cookie
  port: 9001
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: rokepia
    password: 1234
    driver-class-name: oracle.jdbc.driver.OracleDriver
  servlet:
    multipart:
      max-file-size:
        1MB
      max-request-size:
        10MB
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.Oracle12cDialect
    
mybatis:

  #src/main/resources/mapper 아래 있는 모든 xml 파일을 가져온다는 문법
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:config/mybatis-config.xml

